# Generated by Django 4.0.4 on 2022-06-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('merchantId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=3000)),
                ('thumbnailId', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=256)),
                ('website', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('purchaseCount', models.IntegerField()),
                ('categoryId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studioapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('merchantId', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=100)),
                ('latitute', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=3000)),
                ('phoneId', models.CharField(max_length=100)),
                ('merchantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.merchantinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('galleryId', models.AutoField(primary_key=True, serialize=False)),
                ('photoLink', models.CharField(max_length=3000)),
                ('merchantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.merchantinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('linkId', models.AutoField(primary_key=True, serialize=False)),
                ('externalLink', models.CharField(max_length=256)),
                ('merchantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.merchantinfo')),
            ],
        ),
    ]
