# Generated by Django 3.2.13 on 2022-06-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('merchantId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('address', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=256, null=True)),
                ('website', models.CharField(max_length=256, null=True)),
                ('categories', models.ManyToManyField(to='studioapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoId', models.AutoField(primary_key=True, serialize=False)),
                ('photoUrl', models.CharField(max_length=3000)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.merchantinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantLocation',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('latitute', models.DecimalField(decimal_places=3, max_digits=10)),
                ('name', models.CharField(max_length=256)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studioapp.merchantinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUrl',
            fields=[
                ('linkId', models.AutoField(primary_key=True, serialize=False)),
                ('externalUrl', models.CharField(max_length=256)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.merchantinfo')),
            ],
        ),
    ]
